ADD custom methods
emmanuellmhango/railsblogapp pull request #2
Opened 2023-02-28 22:16 UTC by emmanuellmhango

I have added the following

- Create model classes for all entities as shown in the.
- Set up associations between models.
 (author_id column in posts table should be the foreign_key for the users table.)
- Create custom methods

2023-02-28 23:07 UTC, franclobo requested changes
Hi @emmanuellmhango, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/222003028-1aaec18b-0f32-4c47-9d59-6a7ca3726af0.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct methods ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 23:07 UTC, franclobo commented on app/models/user.rb
> +  has_many :likes
- [ ] Kindly add 👉🏽 `foreign_key: 'author_id'` for pos,t comments, and likes to match the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).

2023-02-28 23:07 UTC, franclobo commented on app/models/post.rb
> +  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
- [ ] Please 🙏🏽 remove the foreign key here, it should be added to the user model. The user has many posts then the user needs a foreign key to join with the post table.

2023-02-28 23:07 UTC, franclobo commented on app/models/comment.rb
> +  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
- [ ] Please 🙏🏽 remove the foreign key here, it should be added to the user model. As I commented in the post.

2023-02-28 23:07 UTC, franclobo commented on app/models/like.rb
> +  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
- [ ] Please 🙏🏽 remove the foreign key here, it should be added to the user model. As I commented in the post.

2023-03-01 07:47 UTC, Ismailco approved these changes
### Hi @emmanuellmhango, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 09:31 UTC, merged